#!/usr/bin/env node
/**
 * Generate the in-app manual into a bundled TypeScript module.
 *
 * The renderer CSP is `default-src 'self'`, so nothing can be fetched at
 * runtime — and the packaged app does not ship `/docs/` at all. Both push to
 * the same answer: the manual is compiled in at build time, and the generated
 * file is **committed** so a build never depends on the docs tree being there.
 *
 *   node scripts/build-manual.mjs [--check]
 *
 * `--check` regenerates and fails if the committed output differs, which is how
 * CI-less repos notice a stale artifact.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "apps/gui/src/renderer/src/manual/chapters.generated.ts");

/**
 * Curated, not every FRD. An FRD is written for an implementer — requirement
 * ids, file paths, acceptance criteria — and a manual assembled from 24 of them
 * is one nobody reads. These are the ones that describe what the app *does*,
 * each with a title a user would recognise.
 */
const FROM_FRD = [
  ["profiles", "Requirement profiles", "FRD-002-requirement-profiles.md"],
  ["stages", "The six stages", "FRD-007-fixed-six-stage-board.md"],
  ["documents", "Ticket documents", "FRD-003-ticket-documents.md"],
  ["groups", "Epics and horizons", "FRD-001-groups.md"],
  ["proof", "Proof", "FRD-006-typed-proof.md"],
  ["references", "Reference files", "FRD-004-reference-files.md"],
  ["backlog", "The Backlog list", "FRD-011-backlog-list-view.md"],
  ["dispatch", "Dispatching agents", "FRD-010-task-scoped-dispatch.md"],
  ["board-sync", "Sharing the board over Git", "FRD-020-board-git-worktree-sync.md"],
];

/** Everything above the first `## ` heading: the prose, not the requirements. */
function leadProse(md) {
  const body = md.replace(/^---\n[\s\S]*?\n---\n/, "").trim();
  const cut = body.indexOf("\n## ");
  const lead = (cut === -1 ? body : body.slice(0, cut)).trim();
  // Drop the document's own H1 — the chapter supplies its title.
  return lead.replace(/^#\s+.*\n+/, "").trim();
}

const chapters = [];

// 1. Hand-written chapters, in reading order and first.
for (const [id, title, file] of [
  ["getting-started", "Getting started", "getting-started.md"],
  ["troubleshooting", "Troubleshooting", "troubleshooting.md"],
]) {
  const path = join(root, "docs/manual", file);
  if (!existsSync(path)) throw new Error(`Missing hand-written chapter: docs/manual/${file}`);
  chapters.push({ id, title, body: readFileSync(path, "utf8").trim() });
}

// 2. Curated FRD prose.
for (const [id, title, file] of FROM_FRD) {
  const path = join(root, "docs/functional/frd", file);
  if (!existsSync(path)) throw new Error(`Missing FRD for chapter "${id}": ${file}`);
  const body = leadProse(readFileSync(path, "utf8"));
  if (!body) throw new Error(`FRD ${file} has no lead prose — chapter "${id}" would be empty`);
  chapters.push({
    id,
    title,
    body: `${body}\n\n*Full specification: \`docs/functional/frd/${file}\`.*`,
  });
}

// 3. Shortcuts, from the one binding table.
const shortcutsSrc = readFileSync(join(root, "apps/gui/src/shared/shortcuts.ts"), "utf8");
const rows = [...shortcutsSrc.matchAll(
  /\{\s*keys:\s*"([^"]+)",\s*label:\s*"([^"]+)",\s*context:\s*"([^"]+)"\s*\}/g,
)].map((m) => ({ keys: m[1], label: m[2], context: m[3] }));
if (rows.length === 0) throw new Error("Parsed no shortcuts — the table's shape changed");

chapters.push({
  id: "shortcuts",
  title: "Keyboard shortcuts",
  body: [
    "Generated from the app's own binding table, so it cannot drift from what",
    "the keys actually do.",
    "",
    "| Keys | Does | Where |",
    "|---|---|---|",
    ...rows.map((r) => `| \`${r.keys}\` | ${r.label} | ${r.context} |`),
  ].join("\n"),
});

const out = `// GENERATED by scripts/build-manual.mjs — do not edit.
//
// Committed deliberately: the renderer CSP forbids fetching anything at
// runtime, and the packaged app does not ship /docs/. Regenerate with
// \`npm run build:manual\`; \`--check\` fails when this file is stale.

export interface ManualChapter {
  id: string;
  title: string;
  /** Markdown. */
  body: string;
}

export const MANUAL_CHAPTERS: readonly ManualChapter[] = Object.freeze(${JSON.stringify(chapters, null, 2)});
`;

if (process.argv.includes("--check")) {
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== out) {
    console.error("manual: chapters.generated.ts is stale — run `npm run build:manual`.");
    process.exit(1);
  }
  console.log(`manual: up to date (${chapters.length} chapters)`);
} else {
  writeFileSync(OUT, out, "utf8");
  console.log(`manual: wrote ${chapters.length} chapters -> ${OUT}`);
}
